version: '2.1'
services:
  dev:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      DJANGO_DEBUG: 'true'
      DJANGO_DB_HOST: 'db'
      DJANGO_DB_PASSWORD: 'Topfji12348-ru12344hnj%'
    command: ./manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - ./src:/usr/src/app
  db:
    image: postgres:11-alpine
    environment:
      POSTGRES_DB: 'quiz'
      POSTGRES_USER: 'quiz'
      POSTGRES_PASSWORD: 'Topfji12348-ru12344hnj%'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
