# Generated by Django 3.0.1 on 2019-12-28 12:28

from django.db import migrations


def generate_superuser(apps, schema_editor):
    from django.contrib.auth.models import User

    User.objects.create_superuser(
        username='root',
        email=None,
        password='12345',
        last_login='2000-01-01',
    )


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.RunPython(generate_superuser)
    ]
